### ISSUE TITLE
"connection closed by remote host" (JRuby / Capistrano)

### ISSUE THREAD

**Issue by thbar** [capistrano/sshkit#488]
I am experiencing an error when deploying a Capistrano-enabled via JRuby. 

This used to work. I haven't more information yet, except it may have appeared after a JRuby or a SSHKit/Capistrano upgrade, unsure at this point, but I will comment later if I find the culprit.

Versions:
* JRuby 9.2.13.0
* SSHKit 1.21.1
* Deploying from Mac OS X 10.14.6

```
$ bundle exec cap production deploy
warning: thread "Ruby-0-Thread-2: /Users/thbar/.rbenv/versions/jruby-9.2.13.0/lib/ruby/gems/shared/gems/sshkit-1.21.1/lib/sshkit/runners/parallel.rb:10" terminated with exception (report_on_exception is true):
SSHKit::Runner::ExecuteError: Exception while executing as user@X.Y.Z.T: connection closed by remote host
  execute at /Users/thbar/.rbenv/versions/jruby-9.2.13.0/lib/ruby/gems/shared/gems/sshkit-1.21.1/lib/sshkit/runners/parallel.rb:15
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@X.Y.Z.T: connection closed by remote host
```

**Comment by leehambley** [comment]
Can you dry sshkit from master please? I merged a PR

**Comment by thbar** [comment]
I just tried (with commit 692a5f4fc190) but the error is still happening:

```
$ bundle exec cap vagrant deploy
warning: thread "Ruby-0-Thread-2: /Users/thbar/.rbenv/versions/jruby-9.2.13.0/lib/ruby/gems/shared/bundler/gems/sshkit-692a5f4fc190/lib/sshkit/runners/parallel.rb:10" terminated with exception (report_on_exception is true):
SSHKit::Runner::ExecuteError: Exception while executing as user@X.Y.Z.T: connection closed by remote host
  execute at /Users/thbar/.rbenv/versions/jruby-9.2.13.0/lib/ruby/gems/shared/bundler/gems/sshkit-692a5f4fc190/lib/sshkit/runners/parallel.rb:15
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@X.Y.Z.T: connection closed by remote host
```

**Comment by leehambley** [comment]
Since you are deploying to vagrant machine locally, one assumes, maybe there's an actual connection problem? 

Is "vagrant" using IP addresses or hostnames, are you on a VPN, is your machine *definitely* up, and already accepting SSH connections?

**Comment by thbar** [comment]
My obfuscation made things less clear - I actually made 2 different attempts:
- The first one to production, connects via a VPN to a Ubuntu machine, by using its IP, to a machine which was up (I switched to MRI right after, and managed to deploy successfully)
- The second one is to a vagrant VM (VirtualBox), which is accepting SSH connections

I'll make further investigation (including upgrading JRuby just in case), and will share my findings here.

**Comment by thbar** [comment]
I am also seeing this problem on another use-case apparently (unrelated to capistrano, but using net/sftp to target an even different server). Investigating, will report back.

**Comment by thbar** [comment]
@leehambley after investigating, it turns out this is not caused by `sshkit` but instead is a problem due to an upgrade of `net/ssh` from `5.2.0` to `6.1.0`.

It is probably a mis-configuration or other client-specific trouble.

I'll close the current ticket, sorry for the noise & thanks for your replies!
